from enum import Enum

class Gender(Enum):
    MEN = "men"
    WOMEN = "women"

class PracticeLevel(Enum):
    NOVICE = "NOVICE"
    ENTHUSIAST = "ENTHUSIAST"
    COMPETITIVE = "COMPETITIVE"
    PRO = "PRO"

class ActivityFileType(Enum):
    GPX = "gpx"
    TCX = "tcx"
    FIT = "fit"

class ConnectorType(Enum):
    STRAVA = "STRAVA"
    FILE = "FILE"

class SlopeProfile(Enum):
    FLAT = "FLAT"
    HILLY = "HILLY"

class ActivityFlag(Enum):
    # Time
    MOVING_TIME_GREATER_THAN_ELAPSED = "MOVING_TIME_GREATER_THAN_ELAPSED"
    # Speed
    SPEED_AVG_ABNORMAL = "SPEED_AVG_ABNORMAL"
    SPEED_STD_DEV_ABNORMAL = "SPEED_STD_DEV_ABNORMAL"
    # Elevation
    ASCENT_SPEED_ABNORMAL = "ASCENT_SPEED_ABNORMAL"
    # Pace
    PACE_AVG_FASTER_THAN_GAP = "PACE_AVG_FASTER_THAN_GAP"
    # Power
    POWER_AVG_KG_ABNORMAL = "POWER_AVG_KG_ABNORMAL"
    POWER_THRESHOLD_ABNORMAL = "POWER_THRESHOLD_ABNORMAL"
    # Heart-rate
    HR_AVG_ABNORMAL = "HR_AVG_ABNORMAL"
    # Scores
    SCORE_HRSS_PER_HOUR_ABNORMAL = "SCORE_HRSS_PER_HOUR_ABNORMAL"
    SCORE_PSS_PER_HOUR_ABNORMAL = "SCORE_PSS_PER_HOUR_ABNORMAL"
    SCORE_RSS_PER_HOUR_ABNORMAL = "SCORE_RSS_PER_HOUR_ABNORMAL"
    SCORE_SSS_PER_HOUR_ABNORMAL = "SCORE_SSS_PER_HOUR_ABNORMAL"

class ElevateSport(Enum):
    AlpineSki = "AlpineSki"
    AmericanFootball = "AmericanFootball"
    Aquathlon = "Aquathlon"
    BackcountrySki = "BackcountrySki"
    Badminton = "Badminton"
    Baseball = "Baseball"
    Basketball = "Basketball"
    Boxing = "Boxing"
    Canoeing = "Canoeing"
    Cardio = "Cardio"
    Climbing = "Climbing"
    Combat = "Combat"
    Cricket = "Cricket"
    Crossfit = "Crossfit"
    Dance = "Dance"
    Diving = "Diving"
    Drive = "Drive"
    Duathlon = "Duathlon"
    EBikeRide = "EBikeRide"
    Elliptical = "Elliptical"
    ESkateboard = "ESkateboard"
    EUnicycle = "EUnicycle"
    Fishing = "Fishing"
    Flying = "Flying"
    Football = "Football"
    Frisbee = "Frisbee"
    Golf = "Golf"
    Gymnastics = "Gymnastics"
    Handcycle = "Handcycle"
    Handball = "Handball"
    HangGliding = "HangGliding"
    Hike = "Hike"
    HorsebackRiding = "HorsebackRiding"
    IceHockey = "IceHockey"
    IceSkate = "IceSkate"
    InlineSkate = "InlineSkate"
    Kayaking = "Kayaking"
    Kitesurf = "Kitesurf"
    Manual = "Manual"
    MotorSports = "MotorSports"
    Mountaineering = "Mountaineering"
    NordicSki = "NordicSki"
    Orienteering = "Orienteering"
    Other = "Other"
    Paragliding = "Paragliding"
    Ride = "Ride"
    RockClimbing = "RockClimbing"
    RollerSki = "RollerSki"
    Rowing = "Rowing"
    Rugby = "Rugby"
    Run = "Run"
    Sailing = "Sailing"
    Skateboard = "Skateboard"
    SkiTouring = "SkiTouring"
    SkyDiving = "SkyDiving"
    Snorkeling = "Snorkeling"
    Snowboard = "Snowboard"
    Snowmobiling = "Snowmobiling"
    Snowshoe = "Snowshoe"
    Softball = "Softball"
    Squash = "Squash"
    StairStepper = "StairStepper"
    StandUpPaddling = "StandUpPaddling"
    Stretching = "Stretching"
    Surfing = "Surfing"
    Swim = "Swim"
    TableTennis = "TableTennis"
    Tactical = "Tactical"
    TelemarkSki = "TelemarkSki"
    Tennis = "Tennis"
    TrackAndField = "TrackAndField"
    Triathlon = "Triathlon"
    Velomobile = "Velomobile"
    VirtualRide = "VirtualRide"
    VirtualRun = "VirtualRun"
    Volleyball = "Volleyball"
    Wakeboarding = "Wakeboarding"
    Walk = "Walk"
    WaterSkiing = "WaterSkiing"
    WeightTraining = "WeightTraining"
    Wheelchair = "Wheelchair"
    Windsurf = "Windsurf"
    Workout = "Workout"
    Yoga = "Yoga"
